
COPY post (id, acceptedanswerid, answercount, body, commentcount, communityowneddate, creationdate, favoritecount, lastactivitydate, lasteditdate, lasteditoruserid, owneruserid, parentid, posttypeid, score, tags, title, viewcount) FROM stdin;
10	\N	\N	<p>This is a common question by those who have just rooted their phones.  What apps, ROMs, benefits, etc. do I get from rooting?  What should I be doing now?</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	I've rooted my phone.  Now what?  What do I gain from rooting?	\N
11	\N	\N	<p>I have a Google Nexus One with Android 2.2. I didn't like the default SMS-application so I installed Handcent-SMS. Now when I get an SMS, I get notified twice. How can I fix this?</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	I installed another SMS application, now I get notified twice	\N
12	\N	\N	<p>You can turn off notification in your stock Messaging application by going into the settings dialog  (Menu button -> Settings) and unchecking Notifications</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
14	\N	\N	<p>This is a common question by those who have just rooted their phones.  What apps, ROMs, benefits, etc. do I get from rooting?  What should I be doing now?</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	I've rooted my phone.  Now what?  What do I gain from rooting?	\N
15	\N	\N	<p>I have a Google Nexus One with Android 2.2. I didn't like the default SMS-application so I installed Handcent-SMS. Now when I get an SMS, I get notified twice. How can I fix this?</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	I installed another SMS application, now I get notified twice	\N
16	\N	\N	<p>You can turn off notification in your stock Messaging application by going into the settings dialog  (Menu button -> Settings) and unchecking Notifications</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
18	\N	\N	<p>This is a common question by those who have just rooted their phones.  What apps, ROMs, benefits, etc. do I get from rooting?  What should I be doing now?</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	I've rooted my phone.  Now what?  What do I gain from rooting?	\N
19	\N	\N	<p>I have a Google Nexus One with Android 2.2. I didn't like the default SMS-application so I installed Handcent-SMS. Now when I get an SMS, I get notified twice. How can I fix this?</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	I installed another SMS application, now I get notified twice	\N
20	\N	\N	<p>You can turn off notification in your stock Messaging application by going into the settings dialog  (Menu button -> Settings) and unchecking Notifications</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
21	\N	\N	<p>I have a Motorola DROID v1 that is running Froyo (2.2).  I've noticed that if my device sleeps for a while, when I wake it up it will not attempt to connect to the wireless AP in my home.  When I go to the wireless settings section, I see a note next to the AP entry that says 'disabled'.  If I click the entry and select 'connect', it connects right away.  It will remain connected until the next longish sleep, when it is again marked as disabled.</p>\n\n<p>Is there any way to prevent this AP entry from being marked as disabled?</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	Moto Droid v1 disabling primary Wireless AP	\N
22	\N	\N	<p>Open the default messaging application, click the menu button and then Settings. Scroll down and disable <strong>Notifications</strong>.</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
23	\N	\N	<p>I have a Nexus One with Android 2.2. I would like to send two contacts (name+phone nr) to one of my contacts. This is a simple menu-option on my old Sony Ericsson.</p>\n\n<p>How can I do this on Android?</p>\n\n<p>I'm not in the same building as the receiver so I can not use Bluetooth.</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	How do I send a contact via SMS?	\N
24	\N	\N	<p>Does one really need to install a task manager? My phone does slowdown on rare occasions but it's not something that hampers regular usage.</p>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	Do I really need to install a task manager?	\N
25	\N	\N	<p>The clearest answer I've seen is here: <a href="http://www.droidforums.net/forum/droid-applications/8328-how-guide-disable-double-notifications-when-using-handcent-sms.html" rel="nofollow">http://www.droidforums.net/forum/droid-applications/8328-how-guide-disable-double-notifications-when-using-handcent-sms.html</a></p>\n\n<p>Quoting:</p>\n\n<ol>\n<li>Open the "messaging" from the app drawer</li>\n<li>Push the "menu" button(the 2nd button from left on the bottom of your Droid</li>\n<li>Click SETTINGS</li>\n<li>Scroll down and UNCHECK "Notifications"</li>\n<li>To futher disable the mssaging app you can UNCHECK " Auto-Retrieve"(this prevents the "Messaging" App from even downloading messages.</li>\n<li>Exit the app. Rejoice. Live long and Prosper. Yay!</li>\n</ol>\n	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
\.
